export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const ASYNC_INCREMENT = "ASYNC_INCREMENT";
export const CHENGE_THEME = "CHENGE_THEME";
export const DISABLE_BUTTONS = "DISABLE_BUTTONS";
export const ENABLE_BUTTONS = "ENABLE_BUTTONS";
